--[[  Generated by FAF Map Editor                                              ]]--
-- Table of which resources belong to which player, it is sorted in such a way that the first line
-- corresponds to player one, the second to player 2 and so on...

maxPlayerOnMap = 6




-- Line number is 10 + armynumber for the mexes in the table
spwnMexArmy = {		{00,01,02,03,24,25,26,27,28,29,30,31,32,36,40,45,48,49,50,51,52,53,54,55,56,57,58,74,75,76,77,78,79,80,81,82,83,84,85,86,87,89,90,91,92,93,94,95},
                    {04,05,06,07,24,25,28,29,32,36,40,45,48,49,50,51,52,53,54,55,60,61,62,63,64,65,74,75,76,77,78,79,80,81,82,83,84,85,86,87,89,90,91,92,93,94,95},
                    {08,09,10,11,24,25,28,29,32,33,35,36,40,45,48,49,50,51,52,53,54,55,59,66,74,75,76,77,78,79,80,81,82,83,84,85,86,87,89,90,91,92,93,94,95},
                    {12,13,14,15,24,25,28,29,32,36,37,38,39,40,45,48,49,50,51,52,53,54,55,67,68,74,75,76,77,78,79,80,81,82,83,84,85,86,87,89,90,91,92,93,94,95},
                    {16,17,18,19,24,25,28,29,32,36,40,41,42,43,45,48,49,50,51,52,53,54,55,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,89,90,91,92,93,94,95},
                    {20,21,22,23,24,25,28,29,32,36,40,44,45,46,47,48,49,50,51,52,53,54,55,69,70,71,74,75,76,77,78,79,80,81,82,83,84,85,86,87,89,90,91,92,93,94,95},
                    {},
                    {},
                    {},
                    {},
                    {},
                    {},
                    {},
                    {},
                    {},
                    {}}



-- Line number is 30 + armynumber for the hydros in the table
spwnHydroArmy = {	{00},
                    {01},
                    {02},
                    {03},
                    {04},
                    {05},
                    {},
                    {},
                    {},
                    {},
                    {},
                    {},
                    {},
                    {},
                    {},
                    {}}


-- RESOURCE SCALING OPTIONS
-- exampleMexes = {{1,2},{3,4},{5,6}},        -- exampleMexes = {{1,2}}
-- exampleMexes = {{a},{b},{c}},              -- exampleMexes = {{a}}
-- option key=1 : removes a+b+c               -- option key=1 : removes a
-- option key=2 : spawn a, removes b+c        -- option key=2 : spawns a
-- option key=3 : spawn a+b, removes c
-- option key=4 : spawn a+b+c

extraHydros = {{}}

extraMexes = {{}}

middleMexes = {{},{},{}}

sideMexes = {{},{},{}}

underwaterMexes = {{},{},{}}

islandMexes = {{},{},{}}

expansionMexes = {{},{},{}}

coreMexes = {{}}

extraBaseMexes = {{}}

topSideMexes = {{},{},{}}

bottomSideMexes = {{},{},{}}

forwardCrazyrushMexes = {}

crazyrushOneMexes = {}

